config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resource :carriages, only: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :carriages
  end

  resource :search, only: [:new, :create, :show, :edit]
  resources :tickets do
    post :new, on: :member
  end
  resources :routes

end

app/models/route.rb
class Route < ActiveRecord::Base
  validates :title, presence: true
  # Своя валидация на мин кол-во станций в маршруте
  validate :station_count
  # Много :railway_stations, связь через таблицу :railway_stations_routes
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

# Маршрут может иметь много train
  has_many :trains

# Устанавливаем значение перед валидацией
  before_validation :set_title

  protected

  def set_title
    self.title = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end


  def station_count
    if railway_stations.size < 2
      errors.add(:base, "У  маршрута должно быть минимум две станции!")
    end
  end

end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end
end

app/views/admin/routes/_stations_on_the_route.erb
<!-- Безымянные partials -->

<!-- Вот здесь нужно выводить список станций маршрута по порядку, то есть сделать scope с сортировкой по полю station_number. -->
<% if @route.railway_stations.present? %>
  <table>
    <thead>
      <tr>
        <td>Название</td>
        <td>Позиция</td>
        <td>Время прибытия</td>
        <td>Время отправления</td>
      </tr>
    </thead>
    <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
        <tr>
          <td><%= station.title %></td>
          <td>
            <%= form_tag update_position_railway_station_path(station), method: :patch do %>
              <%= number_field_tag :position, station.position_in(@route) %>
              <%= hidden_field_tag :route_id, @route.id %>
          </td>
          <td>
            <%= time_field_tag :arrival_time, station.arrival_time(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
          </td>
          <td>
            <%= time_field_tag :departure_time, station.departure_time(@route) %>
            <%= hidden_field_tag :route_id, @route.id %>
            <%= submit_tag "Изменить" %>
          </td>
          <% end %>
        </tr>
       <% end %>
    </tbody>
  </table>
<% else %>
  Станций на маршруте нет
<% end %>

app/views/admin/routes/_trains_on_the_route.erb
<!-- Безымянные parshials -->

<% if @route.trains.present? %>
  <% @route.trains.each do |train| %>
    <%= train.number %>
  <% end %>
<% else %>
  Поездов на маршруте нет
<% end %>

app/views/admin/routes/edit.html.erb
<%= link_to 'Главная', root_path %>
<h1>Редактироввание маршрута:</h1>

<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
      <%= f.label :railway_station_ids, "Список станций" %>
      <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Просмотреть', [:admin, @route] %>
<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/index.html.erb
<%= link_to 'Главная', root_path %>

<p id="notice"><%= notice %></p>
<h1>Маршруты:</h1>

<table>
  <thead>
    <tr>
      <th>Список:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.title %></td>
        <td><%= link_to 'Показать', admin_route_path(route) %></td>
        <td><%= link_to 'Редактировать', edit_admin_route_path(route) %></td>
        <td><%= link_to 'Удалить', admin_route_path(route), method: :delete, data: { confirm: 'Уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый маршрут', new_admin_route_path %><br>

app/views/admin/routes/new.html.erb
<%= link_to 'Главная', root_path %><br>
<h1>Новый маршрут:</h1>

<!-- Сообщения об ошибках вынесены в 'common/errors' -->
<%= render 'common/errors', resource: @route %>

<%= form_for(@route) do |f| %>
  
  <div class="field">
    <%= f.label :title, "Название маршрута:" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :railway_station_ids, "Список станций" %>
    <%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>


<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/show.html.erb
<%= link_to 'Главная', root_path %>


<p>
  <strong>Маршрут:</strong>
  <%= @route.title %>
</p>
<p>
  <strong>Станции на маршруте:</strong>
  <%= render 'stations_on_the_route' %>
</p>

<p>
  <strong>Поезда на маршруте:</strong>
  <%= render 'trains_on_the_route' %>
</p>


<%= link_to 'Редактировать', edit_admin_route_path(@route) %> |
<%= link_to 'Назад', admin_routes_path %>