config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resource :carriages, only: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :carriages
  end

  resource :search, only: [:new, :create, :show, :edit]
  resources :tickets do
    post :new, on: :member
  end
  resources :routes

end

app/models/carriage.rb
class Carriage < ActiveRecord::Base
  
  belongs_to :train

  # Установка номаера вагона перед валидацией
  before_validation  :set_carriage_number
  validates :number, :top_seats, :bottom_seats, :train_id, presence: true
  #Проверка на уникальность номера вагона
  validates :number, uniqueness: { scope: :train_id }

  # Сортировка вагонов по номеру
  scope :ordered, -> { order(:number) }

  CARRIAGE_TYPES = ['Coupe', 'Econom', 'SV', 'Seating']

  def self.type_carriage
    CARRIAGE_TYPES
  end


protected
  # Сделал по умолчанию в таблице 0
  def set_carriage_number
    carriage_max_number = train.carriages.maximum(:number) || 0
    # carriage_max_number = 0 if carriage_max_number.nil?
    self.number = carriage_max_number + 1
  end

  

end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  # before_action :set_train, only: [:new, :create]

  def index
    @carriages = Carriage.all
  end

  def show
    @carriage = Carriage.find(params[:id])
  end

  
  def new
    @carriage = Carriage.new
  end

 
  def edit
  end


  def create
    @carriage = @train.carriages.new(carriage_params)

    if @carriage.save
      redirect_to @train, notice: 'Вагон создан!'
    else
      render :new
    end
  end


  def update
    if @carriage.update(carriage_params)
      redirect_to @carriage, notice: 'Информация о вагоне обновлена!'
    else
      render :edit
    end
  end


  def destroy
    @carriage.destroy
      redirect_to carriages_url, notice: 'Вагон удален!' 
  end

  private
    
    def set_carriage
      @carriage = Carriage.find(params[:id])
    end

    def set_train
      @train = Train.find(params[:train_id])
    end

    
    def carriage_params
      params.require(:carriage).permit(:number, :type_carriage, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, :seat_seats, :train_id)
    end


end

app/views/admin/carriages/_carriage.html.erb
<!-- Безымянные partiials -->
<p>
  Number:<%= carriage.number %><br>
  Train:<%= carriage.train_id %><br>
  Type:<%= carriage.type_carriage %><br>
  Top_seats:<%= carriage.top_seats %><br>
  Bottom_seats:<%= carriage.bottom_seats %><br>
</p>

app/views/admin/carriages/_form.html.erb
<%= form_for [:admin, @train, @carriage] do |f| %>
  
  <!-- Сообщения об ошибках вынесены в 'common/errors' -->
  <%= render 'common/errors', resource: @carriage %>
  
  <div class="field">
    <%= f.label :train_id, "Номер поезда, к которому добавить" %><br>
    
    <%= f.collection_select :train_id, Train.all, :id, :number %>
  </div>

  <div class="field">
    <%= f.label :type_carriage, "Тип вагона:" %>
    <%= f.select :type_carriage, Carriage.type_carriage%>
  </div>

  <div class="field">
    <%= f.label :number, "Номер вагона" %><br>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :top_seats, "Количество верхних мест" %><br>
    <%= f.number_field :top_seats %>
  </div>

  <div class="field">
    <%= f.label :bottom_seats, "Количество нижних мест" %><br>
    <%= f.number_field :bottom_seats %>
  </div>

  <div class="field">
    <%= f.label :side_top_seats, "Количество боковых верхних мест" %><br>
    <%= f.number_field :side_top_seats %>
  </div>

  <div class="field">
    <%= f.label :side_bottom_seats, "Количество боковых нижних мест" %><br>
    <%= f.number_field :side_bottom_seats %>
  </div>

  <div class="field">
    <%= f.label :seat_seats, "Количество сидячих мест" %><br>
    <%= f.number_field :seat_seats %>
  </div>

  <div class="actions">
     <%= f.submit %>
  </div>
<% end %>

app/views/admin/carriages/edit.html.erb
<%= link_to 'Главная', root_path %>

<h2>Изменить вагон:</h2>

<%= render 'form' %>

<%= link_to 'Просмотреть', [:admin, @train] %>
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/carriages/index.html.erb
<%= link_to 'Главная', root_path %>

<%= link_to 'Создать новый вагон', new_admin_carriage_path %><br>
<p id="notice"><%= notice %></p>

<h1>Все вагоны:</h1><br>
<%= render @carriages %><br>

app/views/admin/carriages/new.html.erb
<h1>Новый вагон:</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_carriages_path %>

<%= link_to 'Главная', root_path %>

app/views/admin/carriages/show.html.erb
<%= link_to 'Главная', root_path %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Вагон номер:</strong>
  <%= @carriage.number %>
  <strong>Тип:</strong>
  <% if @carriage.type_carriage.present? %>
      <%= @carriage.type_carriage %>
  <% else %>
      Тип не указан
  <% end %>
<ul>
  <li>
    Верхних мест:
    <% top_seats = @carriage.top_seats.nil? ? 0 : @carriage.top_seats %>
    <%= top_seats %>
  </li>
  <li>
    Нижних мест:
    <% bottom_seats = @carriage.bottom_seats.nil? ? 0 : @carriage.bottom_seats %>
    <%= bottom_seats %>
  </li>
  <li>
    Верхних боковых мест:
    <% side_top_seats = @carriage.side_top_seats.nil? ? 0 : @carriage.side_top_seats %>
    <%= side_top_seats %>
  </li>
  <li>
    Нижних боковых мест:
    <% side_bottom_seats = @carriage.side_bottom_seats.nil? ? 0 : @carriage.side_bottom_seats %>
    <%= side_bottom_seats %>
  </li>
  <li>
    Сидячих мест :
    <% seat_seats = @carriage.seat_seats.nil? ? 0 : @carriage.seat_seats %>
    <%= seat_seats %>
  </li>
  <li>
    Всего мест:
    <%= top_seats + bottom_seats + side_top_seats + side_bottom_seats + seat_seats %>
  </li>
</ul>
</p>

<p>
<%= link_to 'Просмотреть', [:admin, @carriage] %>
<%= link_to 'Редактировать', edit_admin_carriage_path(@carriage) %>
<%= link_to 'Удалить', [:admin, @carriage], method: :delete, data: { confirm: 'Точно удалить?' } %><br>
<%= link_to 'Список поездов', admin_trains_path %><br>
<%= link_to 'Назад', admin_carriages_path %>
</p>