config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resource :carriages, only: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :carriages
  end

  resource :search, only: [:new, :create, :show, :edit]
  resources :tickets do
    post :new, on: :member
  end
  resources :routes

end

app/models/search.rb
class Search

  include ActiveModel::Model

  attr_accessor :start_station_id, :end_station_id, :railway_stations_both
  attr_reader :result

  validates :start_station_id, :end_station_id, presence: true

  def start_station
    @start_station ||= RailwayStation.find(start_station_id)
  end

  def end_station
    @end_station ||= RailwayStation.find(end_station_id)
  end

  def run
    if valid?
      # @railway_stations_both = RailwayStation.includes(:start_station_id, :end_station_id)
      # @result = Train.includes(route: :railway_stations).where(RailwayStation.includes(:start_station_id, :end_station_id)) 
       # puts @result
      # @result = Train.includes(route: :railway_stations).where(railway_stations: {id: start_station_id} & {id: end_station_id}) 
       
      @result = Train.includes(route: :railway_stations).where(railway_stations: { id: start_station_id }) &
                Train.includes(route: :railway_stations).where(railway_stations: { id: end_station_id })
    
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search ||= Search.new
  end

  def create
    @search = Search.new(search_params)
    @search.run
    render :show
  end

  protected

  def search_params
    params.require(:search).permit(:start_station_id, :end_station_id)
  end
end

app/views/searches/show.html.erb
<%= link_to 'Главная', root_path %><br>

<h2>Поиск билетов</h2>

<%= form_for(@search, method: :post, url: search_path) do |f| %>

  <!-- Сообщения об ошибках вынесены в 'common/errors' -->
  <%= render 'common/errors', resource: @search %>

    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :start_station_id, 'Станция отправления:' %>
          <%= f.collection_select :start_station_id, RailwayStation.all.ordered_by_title, :id, :title, {} %>
        </div>
        <div class="col-md-4">
          <%= f.label :end_station_id, 'Станция назначения:' %>
          <%= f.collection_select :end_station_id, RailwayStation.all.ordered_by_title, :id, :title, {} %>
        </div>
        <div class="col-md-4">
          <%= f.submit 'Найти' %>
        </div>
      </div>
    </div>
 <% end %>   
    <% if @search.result %>
        <% if @search.result.empty?  %>
            <p ><h4 class="text-danger">Подходящих маршрутов не найдено.Выберите другие станции.</h4></p>
          <%else%>
            <h2><%= "Результаты:" %></h2>
              <table class="table table-hover">
                <thead>
                  <tr>
                    <td><%= "Поезд №:" %></td>
                    <td><%= "Маршрут:" %></td>
                    <td><%= "Время отправления:" %></td>
                    <td><%= "Время прибытия:" %></td>
                  </tr>
                </thead>
                <tbody>
                <% @search.result.each do |t| %>
                    <tr>
                      <td><%= t.number %></td>
                      <td><%= t.route.title %></td>
                      <td><%= @search.start_station.arrival_time(t.route) %></td>
                      <td><%= @search.end_station.departure_time(t.route) %></td>
                      <td>
                        <!-- form_tag({controller: "tickets", action: "new"}, method: "post") -->
                        <%= form_tag (new_ticket_path) do %> 
                        <%= hidden_field_tag :start_station_id, @search.start_station_id %>
                            <%= hidden_field_tag :end_station_id, @search.end_station_id %>
                            <%= hidden_field_tag :train_id, t.id %>
                            <%= submit_tag "Купить билет" %>
                        <% end %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        <% end %>
    <% end %>