config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do

    resources :railway_stations do
      patch :update_position, on: :member
    end

    resource :carriages, only: [:new, :create]

    resources :trains do
      resources :carriages, shallow: true
    end

    resources :carriages
  end

  resource :search, only: [:new, :create, :show, :edit]
  resources :tickets do
    post :new, on: :member
  end
  resources :routes

end

app/models/train.rb
class Train < ActiveRecord::Base
  
  # Принадлежит route
  belongs_to :route

  # Принадлежит railway_station
  # belongs_to :railway_station

  # Принадлежит railway_station, переделано в current_station + указание RailwayStation
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id

  # Имеет много tickets
  has_many :tickets
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to admin_train_path(@train), notice: 'Поезд создан!' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_train_path(@train), notice: 'Информация о поезде отредактирована!' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_train_path, notice: 'Поезд удален!' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def train_params
      params.require(:train).permit(:number, :sort_order, :route_id)
    end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, @train] do |f| %>
  
  <!-- Сообщения об ошибках вынесены в 'common/errors' -->
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number, "Номер поезда:" %><br>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :route, "Маршрут:" %><br>
    <%= f.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="field">
    <%= f.label :sort_order, 'Отсортировать с головы состава!' %>
    <%= f.check_box :sort_order %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<%= link_to 'Главная', root_path %>
<!-- Безымянные partials -->
<tr>
  <td><%= train.number %></td>
  
  <td><%= link_to 'Показать', admin_train_path(train) %></td>
  <td><%= link_to 'Редактировать', edit_admin_train_path(train) %></td>
  <td><%= link_to 'Удалить', admin_train_path(train), method: :delete, data: { confirm: 'Точно удалить?' } %></td>
</tr>

app/views/admin/trains/_train_carriages.erb
<!-- Безымянные partials -->
<p>
  <strong>Всего:</strong>
  <%= @train.carriages.length %>
</p>
<p>
  <strong>Вагоны по типам:</strong><br>
  <p>
    <% @train.carr_by_type.each do |type| %>
      Тип:<%= "#{type[0]} - #{type[1]} " %>
          <% @train.places_by_type(type[0]).each do |seat| %>
              <%= "#{seat[0]}: #{seat[1]}" %><br>
          <% end %>    
    <% end %>
  </p>
</p>

app/views/admin/trains/_train_route.erb
<!-- Безымянные parshials -->

  <% if @train.route.present? %>
    <%= @train.route.title %>
  <% else %>
    Маршрут не назначен
  <% end %>

app/views/admin/trains/edit.html.erb
<h1>Редактирование  Поезда:</h1>

<%= render 'form' %>

<%= link_to 'Просмотреть', [:admin, @train] %> |
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/index.html.erb
<%= link_to 'Главная', root_path %>
<p id="notice"><%= notice %></p>

<h1>Все поезда:</h1>

<table>
  <thead>
    <tr>
      <th>Номер:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Новый поезд', new_admin_train_path %><br>

app/views/admin/trains/new.html.erb
<h1>Новый Поезд:</h1>

<%= render 'form' %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<%= link_to 'Главная', root_path %><br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер поезда:</strong><br>
  <%= render @train %>
</p>

<p>
  <strong>Маршрут поезда:</strong><br>
  <%= render 'train_route' %>
</p>

<p>
  <strong>Вагоны у поезда:</strong><br>
  <%= render 'train_carriages' %>
</p>

 <p>
  <strong>Список вагонов:</strong>
<ul>
  <% @train.carriages.ordered.each do |carriage| %>
      <li>
        <%= link_to "Вагон № #{carriage.number}", carriage %>
      </li>
  <% end %>
</ul>
</p>

<%= link_to 'Добавить вагон', new_admin_train_carriage_path(@train) %>
<%= link_to 'Редактировать', edit_admin_train_path(@train) %>
<%= link_to 'Назад', admin_trains_path %>